version: '3.8'

services:
  mysqlsrv:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "marlon"
      MYSQL_DATABASE: "dbpadrao"
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\1545 IRON V4\Desktop\Dev\docker\volumes\mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
